### PR TITLE
Replace accesses to Bundle.module with .spotifyExampleContentModule. Fixes #9

### LINKED ISSUE #9: Xcode Previews crash when using SpotifyAPI as a dependency
Here's an odd one.

My previews currently aren't working. I've generated a diagnostics report and got this:

```
Error Domain=NSCocoaErrorDomain Code=516 "“resource_bundle_accessor.swift” couldn’t be linked to “Intermediates” because an item with the same name already exists." UserInfo={
    NSSourceFilePathErrorKey=/Users/lukas/Library/Developer/Xcode/DerivedData/ElevenTunes-gjysmmlfnagvqcginmznydrhcrcd/Build/Intermediates.noindex/Previews/ElevenTunes/Intermediates.noindex/SpotifyAPI.build/Debug/SpotifyExampleContent.build/DerivedSources/resource_bundle_accessor.swift, 
    NSUserStringVariant=(
        Link
    ), 
    NSDestinationFilePath=/var/folders/hz/m7z40m4x72d08f_7q265dn080000gn/T/previews-diagnostics-20210401-231950/Intermediates/resource_bundle_accessor.swift, 
    NSFilePath=/Users/lukas/Library/Developer/Xcode/DerivedData/ElevenTunes-gjysmmlfnagvqcginmznydrhcrcd/Build/Intermediates.noindex/Previews/ElevenTunes/Intermediates.noindex/SpotifyAPI.build/Debug/SpotifyExampleContent.build/DerivedSources/resource_bundle_accessor.swift, 
    NSUnderlyingError=0x7febb7518620 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}
}
```

I've traced the error back and found [this thread](https://developer.apple.com/forums/thread/664295). Apparently, when declaring views referencing dependencies using Bundle.module, previews crash.

They have a workaround for this, where `Bundle.module` accesses are replaced. I'm not sure how this hasn't been addressed yet months later though...

### PR DESCRIPTION
**Pull request by Ivorforce**
Fixes #9.

### CODE REVIEW

**Comment by Ivorforce** [comment]
It's not a super pretty solution, but here's hoping the underlying error gets fixed by Apple some time in the future and you can undo this commit.

**Comment by Peter-Schorn** [comment]
I just tested this using the unit tests in my library and it couldn't find the bundle. Try running the "ExampleContentTests" test case (Tests/SpotifyWebAPIMainTests/Other Tests/ExampleContentTests.swift)

**Comment by Peter-Schorn** [comment]
Perhaps we need to use `Bundle.module` if all other candidates fail; e.g.:

```swift
static var spotifyExampleContentModule: Bundle = {
        /* The name of your local package, prepended by "LocalPackages_" for iOS and "PackageName_" for macOS. You may have same PackageName and TargetName*/
        let bundleNameIOS = "LocalPackages_SpotifyExampleContent"
        let bundleNameMacOs = "PackageName_SpotifyExampleContent"
        let candidates = [
            /* Bundle should be present here when the package is linked into an App. */
            Bundle.main.resourceURL,
            /* Bundle should be present here when the package is linked into a framework. */
            Bundle(for: SpotifyExampleContentCurrentBundleFinder.self).resourceURL,
            /* For command-line tools. */
            Bundle.main.bundleURL,
            /* Bundle should be present here when running previews from a different package (this is the path to "…/Debug-iphonesimulator/"). */
            Bundle(for: SpotifyExampleContentCurrentBundleFinder.self).resourceURL?.deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent(),
            Bundle(for: SpotifyExampleContentCurrentBundleFinder.self).resourceURL?.deletingLastPathComponent().deletingLastPathComponent(),
        ]
        
        for candidate in candidates {
            let bundlePathiOS = candidate?.appendingPathComponent(bundleNameIOS + ".bundle")
            let bundlePathMacOS = candidate?.appendingPathComponent(bundleNameMacOs + ".bundle")
            if let bundle = bundlePathiOS.flatMap(Bundle.init(url:)) {
                return bundle
            } else if let bundle = bundlePathMacOS.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        return Bundle.module
    }()
```

**Comment by Peter-Schorn** [comment]
Ok, I fixed the issue by changing
```swift
let bundleNameMacOs = "PackageName_SpotifyExampleContent"
```
to
```swift
let bundleNameMacOs = "SpotifyAPI_SpotifyExampleContent"
```

However, this suggests to me that we might need to change this too:
```swift
let bundleNameIOS = "LocalPackages_SpotifyExampleContent"
```

**We must be through in testing this on every platform and in every possible condition (e.g., previews, release builds).**

**Comment by Ivorforce** [comment]
Interesting. This might have to do with how the package is included - SpotifyAPI vs. LocalPackages suggests that the author of this code had his module bound differently. That's a bummer and makes this fix a bit more difficult...

**Pull request closed without merging**
